CREATE PROC [AUDIT].[USP_MAIN_PIPELINE_RUN_DETAILS]
    @PL_NAME VARCHAR(200),
    @SOURCE VARCHAR(200),
    @STATUS VARCHAR(50),
    @STARTTIME DATETIME2(2),
    @ENDTIME DATETIME2(2),
    @RUN_DATE DATE,
    @IS_TO_RAW VARCHAR(10)
AS
BEGIN
    DECLARE @MaxID AS INT;
    DECLARE @PREV_ENDTIME AS DATETIME2(2)

    IF EXISTS (SELECT * FROM [AUDIT].[MAIN_PIPELINE_RUN_DETAILS])
        SET @MaxID = (SELECT MAX(PL_ID) FROM [AUDIT].[MAIN_PIPELINE_RUN_DETAILS]);
    ELSE
        SET @MaxID = 0;

    IF @IS_TO_RAW = 1
    BEGIN
        UPDATE AUDIT.MAIN_PIPELINE_RUN_DETAILS
        SET IS_LATEST_RUN = 0
        WHERE SOURCE = @SOURCE
    END

    SELECT @PREV_ENDTIME = MAX(ENDTIME)
    FROM AUDIT.MAIN_PIPELINE_RUN_DETAILS
    WHERE IS_LATEST_RUN = 1 AND SOURCE = @SOURCE

    INSERT INTO [AUDIT].[MAIN_PIPELINE_RUN_DETAILS]
    (
        PL_ID,
        PL_NAME,
        SOURCE,
        STATUS,
        STARTTIME,
        ENDTIME,
        DURATION,
        RUN_DATE,
        IS_LATEST_RUN
    )
    SELECT
        @MaxID + 1 AS PL_ID,
        @PL_NAME,
        @SOURCE,
        @STATUS,
        CASE
            WHEN @STATUS = 'SKIPPED' THEN NULL
            WHEN @IS_TO_RAW = 1 THEN @STARTTIME
            WHEN @PREV_ENDTIME IS NULL THEN NULL
            ELSE @PREV_ENDTIME
        END AS STARTTIME,
        CASE
            WHEN @STATUS = 'SKIPPED' THEN NULL
            ELSE @ENDTIME
        END AS ENDTIME,
        CASE 
            WHEN @ENDTIME IS NULL THEN '00:00:00'
            ELSE CONVERT(TIME, DATEADD(SECOND, CONVERT(INT, DATEDIFF(SECOND, COALESCE(@PREV_ENDTIME, @STARTTIME), @ENDTIME)), '00:00:00'))
        END AS DURATION,
        CAST(@RUN_DATE AS DATE) AS RUN_DATE,
        1 AS IS_LATEST_RUN
END