CREATE TABLE [AUDIT].[MASTER_TABLE_LIST] (

	[ID] int NULL, 
	[SOURCE] varchar(100) NULL, 
	[SOURCE_TABLE_SCHEMA] varchar(100) NULL, 
	[SOURCE_TABLE_NAME] varchar(100) NULL, 
	[DESTINATION] varchar(100) NULL, 
	[FILE_NAME] varchar(100) NULL, 
	[FILE_TYPE] varchar(100) NULL, 
	[DESTINATION_TABLE_SCHEMA] varchar(100) NULL, 
	[DESTINATION_TABLE_NAME] varchar(100) NULL, 
	[LOAD_TYPE] varchar(100) NULL, 
	[INCREMENTAL_COLUMN] varchar(100) NULL, 
	[STORED_PROCEDURE] varchar(100) NULL, 
	[SQL_QUERY] varchar(100) NULL, 
	[PRIMARY_COLUMN_NAME] varchar(100) NULL, 
	[IN_CLEAN] int NULL, 
	[HANDLE_DELETES] int NULL
);

