CREATE TABLE [AUDIT].[MASTER_CONTROL_TABLE] (

	[ID] varchar(8000) NULL, 
	[SOURCE] varchar(8000) NULL, 
	[SOURCE_TABLE_SCHEMA] varchar(8000) NULL, 
	[SOURCE_TABLE_NAME] varchar(8000) NULL, 
	[FILE_PATH] varchar(8000) NULL, 
	[FILE_NAME] varchar(8000) NULL, 
	[FILE_TYPE] varchar(8000) NULL, 
	[DESTINATION_TABLE_SCHEMA] varchar(8000) NULL, 
	[DESTINATION_TABLE_NAME] varchar(8000) NULL, 
	[LOAD_TYPE] varchar(8000) NULL, 
	[INCREMENTAL_COLUMN] varchar(8000) NULL, 
	[STORED_PROCEDURE] varchar(8000) NULL, 
	[SQL_QUERY] varchar(8000) NULL, 
	[PRIMARY_COLUMN_NAME] varchar(8000) NULL, 
	[IN_CLEAN] varchar(8000) NULL, 
	[HANDLE_DELETES] varchar(8000) NULL, 
	[MAX_INCREMENTAL_VALUE] varchar(8000) NULL
);

