CREATE TABLE [AUDIT].[SEMANTIC_RELATIONSHIPS] (

	[REL_ID] int NULL, 
	[SEMANTIC_MODEL] varchar(100) NULL, 
	[FROM_TABLE] varchar(100) NULL, 
	[FROM_COLUMN] varchar(100) NULL, 
	[TO_TABLE] varchar(100) NULL, 
	[TO_COLUMN] varchar(100) NULL, 
	[REL_CROSS_FILTER_BEHAVIOR] int NULL, 
	[REL_IS_ACTIVE] int NULL, 
	[FROM_CARDINALITY] varchar(5) NULL, 
	[TO_CARDINALITY] varchar(5) NULL, 
	[LAST_MODIFIED] datetime2(2) NULL
);

